using IBS.DataAccess.Data;
using IBS.DataAccess.Repository.IRepository;
using IBS.Models;
using IBS.Models.Filpride.Books;
using IBS.Models.Filpride.MasterFile;
using IBS.Services.Attributes;
using IBS.Utility.Constants;
using IBS.Utility.Helpers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;
using System.Security.Claims;

namespace IBSWeb.Areas.Filpride.Controllers
{
    [Area(nameof(Filpride))]
    [CompanyAuthorize(nameof(Filpride))]
    [DepartmentAuthorize(SD.Department_Accounting, SD.Department_RCD)]
    public class MasterFileController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ILogger<MasterFileController> _logger;

        public MasterFileController(
            ApplicationDbContext dbContext,
            UserManager<ApplicationUser> userManager,
            IUnitOfWork unitOfWork,
            ILogger<MasterFileController> logger)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _logger = logger;
        }

        #region -- Helper Methods --

        private string GetUserFullName()
        {
            return User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.GivenName)?.Value
                   ?? User.Identity?.Name!;
        }

        private async Task<string?> GetCompanyClaimAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null) return null;

            var claims = await _userManager.GetClaimsAsync(user);
            return claims.FirstOrDefault(c => c.Type == "Company")?.Value;
        }

        #endregion

        #region -- Main Excel Generation Method --

        [HttpGet]
        public async Task<IActionResult> GenerateExcel(string masterFileType, CancellationToken cancellationToken)
        {
            try
            {
                var extractedBy = GetUserFullName();
                var companyClaims = await GetCompanyClaimAsync();

                if (companyClaims == null)
                {
                    return BadRequest("Company claim not found");
                }

                // Generate Excel based on master file type
                var result = masterFileType.ToLower() switch
                {
                    "customer" => await GenerateCustomerExcel(extractedBy, companyClaims, cancellationToken),
                    _ => throw new ArgumentException($"Invalid master file type: {masterFileType}")
                };

                if (result.stream == null)
                {
                    TempData["info"] = "No Record Found";
                    return RedirectToAction("Index", "Home");
                }

                // Audit Trail
                FilprideAuditTrail auditTrail = new(
                    extractedBy,
                    $"Generate {masterFileType} master file excel",
                    $"{masterFileType} Master File",
                    companyClaims
                );
                await _unitOfWork.FilprideAuditTrail.AddAsync(auditTrail, cancellationToken);
                await _unitOfWork.SaveAsync(cancellationToken);

                return File(result.stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", result.fileName);
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                _logger.LogError(ex, "Failed to generate {MasterFileType} master file excel. Error: {ErrorMessage}, Stack: {StackTrace}. Generated by: {UserName}",
                    masterFileType, ex.Message, ex.StackTrace, _userManager.GetUserName(User));
                return RedirectToAction("Index", "Home");
            }
        }

        #endregion

        #region -- Customer Master File --

        private async Task<(MemoryStream? stream, string fileName)> GenerateCustomerExcel(
            string extractedBy, 
            string company, 
            CancellationToken cancellationToken)
        {
            var customers = await _dbContext.FilprideCustomers
                .Where(c => c.Company == company)
                .OrderBy(c => c.CustomerCode)
                .ToListAsync(cancellationToken);

            if (!customers.Any())
            {
                return (null, string.Empty);
            }

            var columns = new List<ColumnDefinition>
            {
                new() { Header = "CUSTOMER CODE", ValueSelector = c => ((FilprideCustomer)c).CustomerCode ?? "" },
                new() { Header = "CUSTOMER NAME", ValueSelector = c => ((FilprideCustomer)c).CustomerName },
                new() { Header = "CUSTOMER ADDRESS", ValueSelector = c => ((FilprideCustomer)c).CustomerAddress, WrapText = true },
                new() { Header = "TIN NO", ValueSelector = c => ((FilprideCustomer)c).CustomerTin },
                new() { Header = "BUSINESS STYLE", ValueSelector = c => ((FilprideCustomer)c).BusinessStyle ?? "" },
                new() { Header = "ZIP CODE", ValueSelector = c => ((FilprideCustomer)c).ZipCode ?? "" },
                new()
                {
                    Header = "CREDIT LIMIT",
                    ValueSelector = c => ((FilprideCustomer)c).CreditLimit,
                    NumberFormat = "#,##0.0000",
                    Alignment = ExcelHorizontalAlignment.Right
                },
                new()
                {
                    Header = "CREDIT LIMIT AS OF TODAY",
                    ValueSelector = c => ((FilprideCustomer)c).CreditLimitAsOfToday,
                    NumberFormat = "#,##0.0000",
                    Alignment = ExcelHorizontalAlignment.Right
                },
                new() { Header = "HAS BRANCH", ValueSelector = c => ((FilprideCustomer)c).HasBranch ? "Yes" : "No" },
                new() { Header = "HAS MULTIPLE TERMS", ValueSelector = c => ((FilprideCustomer)c).HasMultipleTerms ? "Yes" : "No" },
                new() { Header = "STATION CODE", ValueSelector = c => ((FilprideCustomer)c).StationCode ?? "" },
                new() { Header = "TYPE", ValueSelector = c => ((FilprideCustomer)c).Type },
                new()
                {
                    Header = "COMMISSION RATE",
                    ValueSelector = c => ((FilprideCustomer)c).CommissionRate,
                    NumberFormat = "0.00%",
                    Alignment = ExcelHorizontalAlignment.Right
                },
                new() { Header = "IS ACTIVE", ValueSelector = c => ((FilprideCustomer)c).IsActive ? "Active" : "Inactive" },
                new()
                {
                    Header = "CREATED DATE",
                    ValueSelector = c => ((FilprideCustomer)c).CreatedDate,
                    NumberFormat = "MMM/dd/yyyy"
                },
                new() { Header = "CREATED BY", ValueSelector = c => ((FilprideCustomer)c).CreatedBy ?? "" },
                new()
                {
                    Header = "EDITED DATE",
                    ValueSelector = c => ((FilprideCustomer)c).EditedDate,
                    NumberFormat = "MMM/dd/yyyy"
                },
                new() { Header = "EDITED BY", ValueSelector = c => ((FilprideCustomer)c).EditedBy ?? "" }
            };

            var customWidths = new Dictionary<string, double>
            {
                { "CUSTOMER NAME", 40 },
                { "CUSTOMER ADDRESS", 50 },
                { "BUSINESS STYLE", 30 }
            };

            return await BuildExcelFile(
                customers,
                "Customer Master File",
                "Customer_MasterFile",
                extractedBy,
                company,
                columns,
                customWidths,
                2,
                cancellationToken
            );
        }

        #endregion

        #region -- Core Excel Building Logic --

        private async Task<(MemoryStream stream, string fileName)> BuildExcelFile<T>(
            List<T> data,
            string reportTitle,
            string fileNamePrefix,
            string extractedBy,
            string company,
            List<ColumnDefinition> columns,
            Dictionary<string, double>? customColumnWidths,
            int freezeAtColumn,
            CancellationToken cancellationToken) where T : class
        {
            using var package = new ExcelPackage();
            var worksheet = package.Workbook.Worksheets.Add(reportTitle.Replace(" ", ""));

            // Set report title
            var titleRange = worksheet.Cells["A1:B1"];
            titleRange.Merge = true;
            titleRange.Value = reportTitle.ToUpper();
            titleRange.Style.Font.Size = 13;
            titleRange.Style.Font.Bold = true;

            // Set metadata
            worksheet.Cells["A2"].Value = "Extracted By: ";
            worksheet.Cells["B2"].Value = extractedBy;
            worksheet.Cells["A3"].Value = "Company: ";
            worksheet.Cells["B3"].Value = company;
            worksheet.Cells["A4"].Value = "Date Generated: ";
            worksheet.Cells["B4"].Value = DateTimeHelper.GetCurrentPhilippineTime();
            worksheet.Cells["B4"].Style.Numberformat.Format = "MMM/dd/yyyy hh:mm:ss AM/PM";

            // Set column headers (Row 6)
            int headerRow = 6;
            int columnCount = columns.Count;

            for (int i = 0; i < columnCount; i++)
            {
                worksheet.Cells[headerRow, i + 1].Value = columns[i].Header;
            }

            // Apply styling to the header row
            using (var range = worksheet.Cells[headerRow, 1, headerRow, columnCount])
            {
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(Color.LightGray);
                range.Style.Font.Bold = true;
                range.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                range.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                range.Style.Border.Right.Style = ExcelBorderStyle.Thin;
                range.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                range.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
            }

            // Populate data rows
            int row = headerRow + 1;
            foreach (var item in data)
            {
                for (int col = 0; col < columnCount; col++)
                {
                    var columnDef = columns[col];
                    var cellValue = columnDef.ValueSelector(item);
                    var cell = worksheet.Cells[row, col + 1];

                    cell.Value = cellValue;

                    if (!string.IsNullOrEmpty(columnDef.NumberFormat))
                    {
                        cell.Style.Numberformat.Format = columnDef.NumberFormat;
                    }

                    if (columnDef.WrapText)
                    {
                        cell.Style.WrapText = true;
                    }

                    cell.Style.HorizontalAlignment = columnDef.Alignment;
                }
                row++;
            }

            // Auto-fit columns
            worksheet.Cells.AutoFitColumns();

            // Apply custom column widths if specified
            if (customColumnWidths != null)
            {
                foreach (var width in customColumnWidths)
                {
                    var colIndex = columns.FindIndex(c => c.Header == width.Key) + 1;
                    if (colIndex > 0)
                    {
                        worksheet.Column(colIndex).Width = width.Value;
                    }
                }
            }

            // Freeze panes
            worksheet.View.FreezePanes(headerRow + 1, freezeAtColumn);

            // Apply borders to all data
            if (row > headerRow + 1)
            {
                using (var range = worksheet.Cells[headerRow, 1, row - 1, columnCount])
                {
                    range.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                    range.Style.Border.Right.Style = ExcelBorderStyle.Thin;
                    range.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                    range.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                }
            }

            var fileName = $"{fileNamePrefix}_{DateTimeHelper.GetCurrentPhilippineTime():yyyyMMddHHmmss}.xlsx";
            var stream = new MemoryStream();
            await package.SaveAsAsync(stream, cancellationToken);
            stream.Position = 0;

            return (stream, fileName);
        }

        #endregion

        #region -- Column Definition Helper Class --

        private class ColumnDefinition
        {
            public string Header { get; set; } = string.Empty;
            public Func<object, object?> ValueSelector { get; set; } = null!;
            public string? NumberFormat { get; set; }
            public bool WrapText { get; set; }
            public ExcelHorizontalAlignment Alignment { get; set; } = ExcelHorizontalAlignment.Left;
        }

        #endregion
    }
}