using FastReport;
using FastReport.Export.PdfSimple;
using IBS.DataAccess.Data;
using IBS.DataAccess.Repository.IRepository;
using IBS.Models.Filpride.ViewModels;
using IBS.Services.Attributes;
using IBS.Utility.Constants;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IBSWeb.Areas.Filpride.Controllers
{
    [Area(nameof(Filpride))]
    [CompanyAuthorize(nameof(Filpride))]
    public class SalesReportController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        private readonly UserManager<IdentityUser> _userManager;

        private readonly IUnitOfWork _unitOfWork;

        private readonly IWebHostEnvironment _webHostEnvironment;

        private readonly ILogger<SalesInvoiceController> _logger;

        public SalesReportController(ApplicationDbContext dbContext, UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment, ILogger<SalesInvoiceController> logger)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }

        private async Task<string> GetCompanyClaimAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            var claims = await _userManager.GetClaimsAsync(user);
            return claims.FirstOrDefault(c => c.Type == "Company")?.Value;
        }

        [HttpGet]
        public IActionResult SalesReport()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GeneratedSalesReport(ViewModelBook model, CancellationToken cancellationToken)
        {
            var companyClaims = await GetCompanyClaimAsync();
            if (!ModelState.IsValid)
            {
                TempData["error"] = "The submitted information is invalid.";
                return RedirectToAction(nameof(SalesReport));
            }

            try
            {
                var sales = await _unitOfWork.FilprideReport.GetSalesReport(model.DateFrom, model.DateTo, companyClaims, cancellationToken);

                if (sales.Any())
                {
                    var report = new Report();

                    var reportPath = Path.Combine(_webHostEnvironment.WebRootPath, "reports", "SalesReport.frx");
                    report.Report.Load(reportPath);

                    report.Report.SetParameterValue("DateFrom", model.DateFrom.ToString(SD.Date_Format));
                    report.Report.SetParameterValue("DateTo", model.DateTo.ToString(SD.Date_Format));
                    report.Report.Dictionary.RegisterBusinessObject(sales, "SalesReport", 4, true);
                    report.Report.GetDataSource("SalesReport").Enabled = true;

                    await report.PrepareAsync(cancellationToken);

                    using var pdfExport = new PDFSimpleExport();
                    using var stream = new MemoryStream();
                    report.Export(pdfExport, stream);
                    stream.Position = 0;

                    return File(stream.ToArray(), "application/pdf");
                }

                TempData["error"] = "No records found!";
                return RedirectToAction(nameof(SalesReport));
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                _logger.LogError(ex, "Failed to generate sales report. Error: {ErrorMessage}, Stack: {StackTrace}. Generated by: {UserName}",
                    ex.Message, ex.StackTrace, _userManager.GetUserName(User));
                return RedirectToAction(nameof(SalesReport));
            }
        }
    }
}
